name: CI básico

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v6

      - name: Mensaje de prueba
        run: echo "CI funcionando correctamente"

      - name: Verificar HTML
        run: |
          if grep -q "<html" index.html; then
            echo "HTML válido"
          else
            echo "Error en HTML"
            exit 1
          fi